export const LOAD_COLOURS_SUCCESS = 'LOAD_COLOURS_SUCCESS';
export const LOAD_TONES_SUCCESS = 'LOAD_TONES_SUCCESS';
export const LOAD_TYPOGRAPHY_SUCCESS = 'LOAD_TYPOGRAPHY_SUCCESS';
export const LOAD_TYPEFACES_SUCCESS = 'LOAD_TYPEFACES_SUCCESS';
